<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>

    <ImplicitUsings>enable</ImplicitUsings>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>

  <!-- Pacotes compatíveis com WebAssembly -->
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
    <!-- <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.56\st\*.a" /> -->
  </ItemGroup>
  <ItemGroup Condition="!$(DefineConstants.Contains('WINDOWS'))">
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.2" />
  </ItemGroup>
  <ItemGroup Condition="$(DefineConstants.Contains('WASM'))">
    <PackageReference Include="SkiaSharp.Views.Blazor" Version="3.119.2" />
  </ItemGroup>

  <!-- Pacotes aparentemente incompatíveis com WebAssembly -->
  <ItemGroup>
    <!-- Aparentemente também incompatíveis com native AOT -->
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
    <!-- <PackageReference Include="NPOI" Version="2.8.0" /> --> <!-- excel -->
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="10.0.11" />
  </ItemGroup>

  <!-- Pacotes já incluídos no dotnet moderno -->
  <!-- <ItemGroup>
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="9.0.6" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
  </ItemGroup> -->


  <ItemGroup>
    <Compile Remove="Scripts\Kirikiri\KirikiriScnScript.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Scripts\Nexas\Notes.txt" />
    <Content Include="Scripts\Yuris\Notes.txt" />
    <Content Include="names.xml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="template.xlsx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="template.xlsx" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Scripts\Nexas\spm.ksy" />
  </ItemGroup>


  <Target Name="DebugPrint" BeforeTargets="Build">
    <Message Text="Valor de SkiaSharpStaticLibraryPath: '$(SkiaSharpStaticLibraryPath)'" Importance="High" />
  </Target>

</Project>